// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAppAPI.Data;

#nullable disable

namespace QAppAPI.Migrations
{
    [DbContext(typeof(QAppDbContext))]
    [Migration("20240213083231_QApp")]
    partial class QApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QAppAPI.Models.ReactQuation", b =>
                {
                    b.Property<int>("QNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QNumber"));

                    b.Property<string>("QName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QNumber");

                    b.ToTable("reactQuations");
                });
#pragma warning restore 612, 618
        }
    }
}
